# Generated by Django 3.1.2 on 2021-04-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Affiliate Name')),
                ('logo', models.ImageField(blank=True, null=True, unique=True, upload_to='affiliates/logos/', verbose_name='Affiliate Logo')),
                ('website', models.URLField(max_length=150, unique=True, verbose_name='Affiliate Website URL')),
            ],
        ),
    ]
