# Generated by Django 3.1.2 on 2021-04-11 17:33

import apps.affiliations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='logo',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=apps.affiliations.models.logo_path, verbose_name='Affiliate Logo'),
        ),
    ]
