# Generated by Django 3.1.2 on 2021-04-10 20:42

import apps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('authors', models.JSONField(default=list, validators=[apps.validators.JSONSchemaValidator(limit_value={'description': "A list of authors' names (as strings) of a project event.", 'properties': {'items': {'type': 'string'}}, 'schema': 'http://json-schema.org/draft-07/schema#', 'title': 'Project Authors', 'type': 'array'})])),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('CO', 'Complete'), ('IP', 'In Progress'), ('PL', 'Planned'), ('OT', 'Other')], max_length=2)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
