# Generated by Django 3.1.2 on 2021-04-20 22:27

import apps.projects.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.JSONField(default=list, validators=[core.validators.JSONSchemaValidator(limit_value={'description': "A list of authors' names (as strings) of a group project.", 'items': {'pattern': '(^(?!\\s*)$)|(^.*\\S.*$)', 'type': 'string'}, 'minItems': '1', 'schema': 'http://json-schema.org/draft-07/schema#', 'title': 'Project Authors', 'type': 'array'})], verbose_name='Project Authors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=apps.projects.models.image_path, verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and Time of Last Edit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=250, unique=True, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CO', 'Complete'), ('IP', 'In Progress'), ('PL', 'Planned'), ('OT', 'Other')], default='PL', max_length=2, verbose_name='Project Status or Phase'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='External Project URL'),
        ),
    ]
