version: '3.3'

volumes:
    aiatncstatewebsite_data: {}

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/venv/
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env

  frontend:
    container_name: frontend
    image: node:10-alpine
    command: npm run serve
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend:/app
    working_dir: /app
    restart: on-failure

  postgres:
    container_name: db
    image: postgres:10-alpine
    volumes:
      - aiatncstatewebsite_data:/var/lib/postgresql/data
    env_file: .env

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    logging:
      driver: none

  nginx:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none

  redis:
    container_name: redis
    image: redis:alpine

  celery:
    container_name: celery
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/venv/
    env_file: .env
    depends_on:
      - redis
    entrypoint: /celery.sh
    environment:
      - RUNNING_TESTS=n

  celery-beat:
    container_name: celery-beat
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/venv/
    env_file:
      - .env
    depends_on:
      - redis
    entrypoint: /celery-beat.sh
    environment:
      - RUNNING_TESTS=n
