# Generated by Django 3.1.2 on 2021-05-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformbase',
            options={'verbose_name': 'Submitted Contact Form'},
        ),
        migrations.AlterModelOptions(
            name='eventorganizercontactform',
            options={'verbose_name': 'Event Organizer Contact Form'},
        ),
        migrations.AlterModelOptions(
            name='guestspeakercontactform',
            options={'verbose_name': 'Guest Speaker Contact Form'},
        ),
        migrations.AlterModelOptions(
            name='mentorcontactform',
            options={'verbose_name': 'Mentor Contact Form'},
        ),
        migrations.AlterModelOptions(
            name='partnercontactform',
            options={'verbose_name': 'Partner Contact Form'},
        ),
        migrations.AddField(
            model_name='contactformbase',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Time Submitted'),
        ),
    ]
