# Generated by Django 3.1.2 on 2021-05-29 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20210521_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizercontactform',
            name='max_attendees',
            field=models.PositiveSmallIntegerField(default=2, null=True, validators=[django.core.validators.MinValueValidator(2, 'Estimated maximum number of attendees too small.')], verbose_name='Estimated/Desired Maximum Number of Attendees'),
        ),
        migrations.AlterField(
            model_name='eventorganizercontactform',
            name='min_attendees',
            field=models.PositiveSmallIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1, 'Estimated minimum number of attendees too small.')], verbose_name='Estimated/Desired Minimum Number of Attendees'),
        ),
    ]
