# Generated by Django 3.1.2 on 2021-05-29 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20210529_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercontactform',
            name='max_org_size',
            field=models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(2, 'Estimated maximum number of employees too small.')], verbose_name='Estimated Maximum Size of Organization'),
        ),
        migrations.AlterField(
            model_name='partnercontactform',
            name='min_org_size',
            field=models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1, 'Estimated minimum number of employees too small.')], verbose_name='Estimated Minimum Size of Organization'),
        ),
    ]
