# Generated by Django 3.1.2 on 2021-05-29 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20210529_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercontactform',
            name='max_org_size',
            field=models.PositiveIntegerField(default=2, null=True, validators=[django.core.validators.MinValueValidator(2, 'Estimated maximum number of employees too small.')], verbose_name='Estimated Maximum Size of Organization'),
        ),
    ]
