# Generated by Django 3.1.2 on 2022-01-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20210529_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincomment',
            name='comment',
            field=models.TextField(default='', verbose_name='Comment'),
        ),
    ]
