# Generated by Django 3.1.2 on 2021-04-10 20:42

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GS', 'Guest Speaker Presentation'), ('WS', 'Workshop'), ('IP', 'Interview Prep Session'), ('DI', 'Free Form Discussion'), ('PM', 'Group Project Meeting'), ('HM', 'Hackathon Meeting'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Type of Event')),
                ('topics', models.JSONField(default=list, validators=[core.validators.JSONSchemaValidator(limit_value={'description': 'A list of topics (as strings) for an event.', 'properties': {'items': {'type': 'string'}}, 'schema': 'http://json-schema.org/draft-07/schema#', 'title': 'Event Topics', 'type': 'array'})], verbose_name='Event Topics')),
                ('start', models.DateTimeField(verbose_name='Start Date and Time')),
                ('end', models.DateTimeField(verbose_name='End Date and Time')),
                ('calendar_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Calendar Invite Link')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='Virtual Meeting Link')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EM', 'Email'), ('PH', 'Phone'), ('OT', 'Other')], default='EM', max_length=2, verbose_name='Contact Information Type')),
                ('preferred', models.BooleanField(default=False, verbose_name='Preferred Method of Contact')),
                ('value', models.CharField(default='', max_length=50, verbose_name='Contact Value')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='events.event', verbose_name='Associated Event')),
            ],
        ),
    ]
