# Generated by Django 3.1.2 on 2021-04-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='type',
            field=models.CharField(choices=[('EM', 'Email Address'), ('PH', 'Phone Number'), ('OT', 'Other Form of Contact')], default='EM', max_length=2, verbose_name='Contact Information Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('GS', 'Guest Speaker Presentation'), ('WS', 'Workshop'), ('IP', 'Interview Prep Session'), ('DI', 'Free Form Discussion'), ('PM', 'Group Project Meeting'), ('HM', 'Hackathon Meeting'), ('OT', 'Other Event')], default='OT', max_length=2, verbose_name='Type of Event'),
        ),
    ]
