# Generated by Django 3.1.2 on 2021-05-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20210503_0240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
