# Generated by Django 3.1.2 on 2021-04-10 20:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, unique=True, verbose_name='Announcement Title')),
                ('body', models.JSONField(default=list, validators=[core.validators.JSONSchemaValidator(limit_value={'$defs': {'header': {'additionalProperties': False, 'properties': {'content': {'type': 'string'}, 'element': {'enum': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'], 'type': 'string'}}, 'required': ['element', 'content'], 'type': 'object'}, 'horizontalRule': {'additionalProperties': False, 'properties': {'element': {'enum': ['hr'], 'type': 'string'}}, 'required': ['element'], 'type': 'object'}, 'image': {'additionalProperties': False, 'properties': {'alt': {'type': 'string'}, 'element': {'enum': ['img'], 'type': 'string'}, 'url': {'type': 'string'}}, 'required': ['element', 'alt', 'url'], 'type': 'object'}, 'paragraph': {'additionalProperties': False, 'properties': {'content': {'type': 'string'}, 'element': {'enum': ['p'], 'type': 'string'}}, 'required': ['element', 'content'], 'type': 'object'}}, 'description': 'The body, or main content, of an announcement which can contain various HTML elements.', 'items': {'anyOf': [{'$ref': '#/$defs/horizontalRule'}, {'$ref': '#/$defs/paragraph'}, {'$ref': '#/$defs/image'}, {'$ref': '#/$defs/header'}]}, 'schema': 'http://json-schema.org/draft-07/schema#', 'title': 'Announcement Body', 'type': 'array'})], verbose_name='Announcement Body')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Announcement Creation Time/Date')),
            ],
        ),
    ]
