# Generated by Django 3.1.2 on 2021-05-03 20:23

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20210503_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.JSONField(default=list, validators=[core.validators.JSONSchemaValidator(limit_value={'description': 'The body, or main content, of an announcement which can contain various HTML elements.', 'items': {'anyOf': [{'additionalProperties': False, 'properties': {'element': {'enum': ['hr'], 'type': 'string'}}, 'required': ['element'], 'type': 'object'}, {'additionalProperties': False, 'properties': {'content': {'type': 'string'}, 'element': {'enum': ['p'], 'type': 'string'}}, 'required': ['element', 'content'], 'type': 'object'}, {'additionalProperties': False, 'properties': {'alt': {'type': 'string'}, 'element': {'enum': ['img'], 'type': 'string'}, 'url': {'type': 'string'}}, 'required': ['element', 'alt', 'url'], 'type': 'object'}, {'additionalProperties': False, 'properties': {'content': {'type': 'string'}, 'element': {'enum': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'], 'type': 'string'}}, 'required': ['element', 'content'], 'type': 'object'}]}, 'schema': 'http://json-schema.org/draft-07/schema#', 'title': 'Announcement Body', 'type': 'array'})], verbose_name='Announcement Body'),
        ),
    ]
