# Generated by Django 3.1.2 on 2022-02-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_auto_20210507_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Announcement Title'),
        ),
    ]
