# Generated by Django 3.1.2 on 2021-05-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EM', 'Email Address'), ('PH', 'Phone Number'), ('OT', 'Other Form of Contact')], default='EM', max_length=2, verbose_name='Contact Information Type')),
                ('preferred', models.BooleanField(default=False, verbose_name='Preferred Method of Contact')),
                ('value', models.CharField(default='', max_length=50, verbose_name='Contact Value')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='contacts', to='contenttypes.contenttype')),
            ],
        ),
    ]
