# Generated by Django 3.1.2 on 2021-05-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210524_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['-preferred']},
        ),
    ]
